// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	echo "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/router/echo"
	mathsvc "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/router/mathsvc"
	timesvc "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/router/timesvc"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	timesvc.Register(r)

	mathsvc.Register(r)

	echo.Register(r)

}
