// Code generated by hertz generator.

package timesvc

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _timesvcMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettimeMw() []app.HandlerFunc {
	// your code...
	return nil
}
