// Code generated by hertz generator.

package timesvc

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	clients "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/clients"
	timesvc "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/model/timesvc"
)

// GetTime .
// @router /timesvc/time [POST]
func GetTime(ctx context.Context, c *app.RequestContext) {
	var err error
	var req timesvc.TimeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	clients.GenericCall("timesvc", "getTime", ctx, c)
}

// GetDate .
// @router /timesvc/date [POST]
func GetDate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req timesvc.DateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	clients.GenericCall("timesvc", "getDate", ctx, c)
}
