// Code generated by hertz generator.

package mathsvc

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mathsvcMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _multiplyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _subtractMw() []app.HandlerFunc {
	// your code...
	return nil
}
