// Code generated by hertz generator.

package echo

import (
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	clients "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/clients"
	echo "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/model/echo"

	"github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/errors"
	"github.com/phiphi-tan/orbital-api-gateway/kitex_gen/common"
)

// Echo .
// @router /echo/echo [POST]
func Echo(ctx context.Context, c *app.RequestContext) {

	//Binding and Validation of Params
	var err error
	var req echo.Request
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := errors.New(common.Err_MissingParameters)
		resp.ErrMsg = err.Error()
		c.JSON(http.StatusOK, resp)
		return
	}

	clients.GenericCall("echo", "echo", ctx, c)
}
