// Code generated by thriftgo (0.2.11). DO NOT EDIT.

package common

type Err int64

const (
	Err_BadRequest           Err = 10001
	Err_Unauthorized         Err = 10002
	Err_ServerNotFound       Err = 10003
	Err_ServerMethodNotFound Err = 10004
	Err_MissingParameters    Err = 10005
	Err_RequestServerFail    Err = 10006
	Err_ServerHandleFail     Err = 10007
	Err_ResponseUnableParse  Err = 10008
)

func (p Err) String() string {
	switch p {
	case Err_BadRequest:
		return "BadRequest"
	case Err_Unauthorized:
		return "Unauthorized"
	case Err_ServerNotFound:
		return "ServerNotFound"
	case Err_ServerMethodNotFound:
		return "ServerMethodNotFound"
	case Err_MissingParameters:
		return "MissingParameters"
	case Err_RequestServerFail:
		return "RequestServerFail"
	case Err_ServerHandleFail:
		return "ServerHandleFail"
	case Err_ResponseUnableParse:
		return "ResponseUnableParse"
	}
	return "<UNSET>"
}