// Code generated by Kitex v0.5.2. DO NOT EDIT.

package mathsvc

import (
	server "github.com/cloudwego/kitex/server"
	mathsvc "github.com/phiphi-tan/orbital-api-gateway/kitex_gen/mathsvc"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler mathsvc.MathSvc, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
