// Code generated by hertz generator.

package mathsvc

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	clients "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/clients"
	mathsvc "github.com/phiphi-tan/orbital-api-gateway/hertz_gateway/biz/model/mathsvc"
)

// Add .
// @router /mathsvc/add [POST]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mathsvc.AddRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	clients.GenericCall("mathsvc", "add", ctx, c)
}

// Subtract .
// @router /mathsvc/subtract [POST]
func Subtract(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mathsvc.SubtractRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	clients.GenericCall("mathsvc", "subtract", ctx, c)
}

// Multiply .
// @router /mathsvc/multiply [POST]
func Multiply(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mathsvc.MultiplyRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	clients.GenericCall("mathsvc", "multiply", ctx, c)
}
