// Code generated by Kitex v0.5.2. DO NOT EDIT.
package echo

import (
	server "github.com/cloudwego/kitex/server"
	echo "github.com/phiphi-tan/orbital-api-gateway/kitex_gen/echo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler echo.Echo, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
