// Code generated by Kitex v0.5.2. DO NOT EDIT.

package timesvc

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	timesvc "github.com/phiphi-tan/orbital-api-gateway/kitex_gen/timesvc"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetTime(ctx context.Context, req *timesvc.TimeReq, callOptions ...callopt.Option) (r *timesvc.TimeResp, err error)
	GetDate(ctx context.Context, req *timesvc.DateReq, callOptions ...callopt.Option) (r *timesvc.DateResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTimeSvcClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTimeSvcClient struct {
	*kClient
}

func (p *kTimeSvcClient) GetTime(ctx context.Context, req *timesvc.TimeReq, callOptions ...callopt.Option) (r *timesvc.TimeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTime(ctx, req)
}

func (p *kTimeSvcClient) GetDate(ctx context.Context, req *timesvc.DateReq, callOptions ...callopt.Option) (r *timesvc.DateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDate(ctx, req)
}
